# fw2_emu_app.cmake — host versions of WiliBSP's fw2_display_app() and
# fw2_psram_app().
#
# Same arguments and the same validation as bsp/CMakeLists.txt, and the same
# FW2AINFO metadata record (generated by WiliBSP's own tools/gen_uf2_info.py),
# so an app's CMakeLists.txt builds for hardware and for the emulator without
# changes. Instead of a UF2 the result is a host program; the app's main() is
# renamed so the emulator can start first.

function(fw2_display_app target)
    cmake_parse_arguments(PARSE_ARGV 1 APP "" "NAME;VERSION;DESCRIPTION;REPOSITORY" "POWER_ZONES")
    if(NOT APP_NAME)
        set(APP_NAME "${target}")
    endif()
    if(NOT APP_VERSION MATCHES "^[0-9][0-9][0-9]$")
        message(FATAL_ERROR "${target}: VERSION must be exactly three digits (000-999)")
    endif()
    if(NOT APP_DESCRIPTION)
        message(FATAL_ERROR "${target}: DESCRIPTION is required for the App Explorer")
    endif()
    if(NOT APP_REPOSITORY)
        set(APP_REPOSITORY "https://github.com/freewili/wilibsp")
    endif()
    if(APP_NAME MATCHES "[^ -~]" OR APP_DESCRIPTION MATCHES "[^ -~]")
        message(FATAL_ERROR "${target}: NAME and DESCRIPTION must contain printable ASCII only")
    endif()
    string(LENGTH "${APP_NAME}" _name_len)
    string(LENGTH "${APP_DESCRIPTION}" _description_len)
    if(_name_len GREATER 31)
        message(FATAL_ERROR "${target}: NAME exceeds 31 ASCII bytes")
    endif()
    if(_description_len GREATER 127)
        message(FATAL_ERROR "${target}: DESCRIPTION exceeds 127 ASCII bytes")
    endif()

    string(REGEX REPLACE "^0+([0-9])" "\\1" _version_number "${APP_VERSION}")
    set(_zone_numbers SENSORS 1 DISPLAY 2 AUDIO 3 SUBGHZ 4 SDCARD 7 USB_HUB 8
                      RGB_LEDS 10 ANALOG 11 NFC_RFID 13 CAN 15)
    set(_power_zone_mask 0)
    foreach(_zone IN LISTS APP_POWER_ZONES)
        list(FIND _zone_numbers "${_zone}" _idx)
        if(_idx LESS 0)
            message(FATAL_ERROR "${target}: unknown POWER_ZONES entry '${_zone}'")
        endif()
        math(EXPR _idx "${_idx} + 1")
        list(GET _zone_numbers ${_idx} _zone_number)
        math(EXPR _power_zone_mask "${_power_zone_mask} | (1 << (${_zone_number} - 1))")
    endforeach()

    set(_dir "${CMAKE_CURRENT_BINARY_DIR}/${target}_uf2_info")
    file(MAKE_DIRECTORY "${_dir}")
    add_custom_command(
        OUTPUT "${_dir}/${target}_uf2_info.c"
        COMMAND ${Python3_EXECUTABLE} "${FW2_TOOLS_DIR}/gen_uf2_info.py"
                --out "${_dir}/${target}_uf2_info.c"
                --version "${_version_number}"
                --name "${APP_NAME}"
                --description "${APP_DESCRIPTION}"
                --repository "${APP_REPOSITORY}"
                --power-zones "${_power_zone_mask}"
        DEPENDS "${FW2_TOOLS_DIR}/gen_uf2_info.py"
        COMMENT "Generating FW2 app metadata for ${target}"
        VERBATIM)
    target_sources(${target} PRIVATE "${_dir}/${target}_uf2_info.c")
    target_compile_definitions(${target} PRIVATE main=fw2_emu_app_main PICO_TARGET_NAME="${target}")
    set_property(GLOBAL APPEND PROPERTY FW2_EMU_APPS "${target}|${APP_VERSION}|${APP_DESCRIPTION}")

    if(EMSCRIPTEN)
        set_target_properties(${target} PROPERTIES SUFFIX ".js")
        target_link_options(${target} PRIVATE
            "-sASYNCIFY" "-sASYNCIFY_STACK_SIZE=65536"
            # PSRAM lives at 0x11000000-0x117FFFFF as on hardware: start the
            # program's own data above it so that range stays free.
            "-sGLOBAL_BASE=293601280"
            "-sALLOW_MEMORY_GROWTH=1" "-sINITIAL_MEMORY=304mb"
            "-sSTACK_SIZE=1048576"
            "-sEXIT_RUNTIME=0"
            "-sENVIRONMENT=web"
            "-sEXPORTED_RUNTIME_METHODS=callMain"
            "-sINVOKE_RUN=1")
    endif()
endfunction()

function(fw2_psram_app target)
    fw2_display_app(${target} ${ARGN})
endfunction()
